version: 2

models:
  - name: dim_dates
    description: |
      Date dimension table for time-based analysis.
      Contains all dates from 2020-01-01 to one year in the future.
      Includes day, week, month, quarter, and year information with flags for weekends.
    columns:
      - name: date_key
        description: "Surrogate key in YYYYMMDD format (e.g., 20240115)"
        tests:
          - unique
          - not_null
      - name: full_date
        description: "Full date value"
        tests:
          - unique
          - not_null
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
      - name: day_name
        description: "Full day name (e.g., Monday)"
      - name: month
        description: "Month number (1-12)"
      - name: month_name
        description: "Full month name (e.g., January)"
      - name: quarter
        description: "Quarter number (1-4)"
      - name: year
        description: "Year (e.g., 2024)"
      - name: is_weekend
        description: "Boolean flag indicating if date is a weekend"
      - name: is_weekday
        description: "Boolean flag indicating if date is a weekday"

  - name: dim_channels
    description: |
      Channel dimension table containing information about each Telegram channel.
      Includes channel classification (Pharmaceutical, Cosmetics, Medical, Other),
      statistics (total posts, media ratio, average views/forwards),
      and date range of activity.
    columns:
      - name: channel_key
        description: "Surrogate key (auto-incrementing integer)"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Natural key - normalized channel name"
        tests:
          - unique
          - not_null
      - name: channel_title
        description: "Display title of the Telegram channel"
      - name: channel_type
        description: "Classification: Pharmaceutical, Cosmetics, Medical, or Other"
        tests:
          - accepted_values:
              values: ['Pharmaceutical', 'Cosmetics', 'Medical', 'Other']
      - name: total_posts
        description: "Total number of messages from this channel"
        tests:
          - not_null
      - name: messages_with_media
        description: "Number of messages that contain media"
      - name: media_ratio
        description: "Ratio of messages with media (0.0 to 1.0)"
      - name: avg_views
        description: "Average number of views per message"
      - name: avg_forwards
        description: "Average number of forwards per message"
      - name: first_post_date
        description: "Date of the first message from this channel"
      - name: last_post_date
        description: "Date of the most recent message from this channel"
      - name: days_active
        description: "Number of days between first and last post"

  - name: fct_messages
    description: |
      Fact table containing one row per message with foreign keys to dimension tables.
      This is the central fact table in the star schema, containing:
      - Message content and metadata
      - Engagement metrics (views, forwards)
      - Business logic fields (product type, price mentions)
      - Foreign keys to dim_channels and dim_dates
    columns:
      - name: message_id
        description: "Primary key - unique message identifier"
        tests:
          - unique
          - not_null
      - name: channel_key
        description: "Foreign key to dim_channels"
        tests:
          - not_null
          - relationships:
              to: ref('dim_channels')
              field: channel_key
      - name: date_key
        description: "Foreign key to dim_dates"
        tests:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_key
      - name: message_text
        description: "Text content of the message"
      - name: message_length
        description: "Length of message text in characters"
      - name: has_text
        description: "Boolean flag indicating if message has text"
      - name: has_media
        description: "Boolean flag indicating if message contains media"
      - name: has_image
        description: "Boolean flag indicating if message has a downloaded image"
      - name: image_path
        description: "File path to downloaded image"
      - name: view_count
        description: "Number of views on the message"
        tests:
          - not_null
      - name: forward_count
        description: "Number of times the message was forwarded"
        tests:
          - not_null
      - name: mentions_price
        description: "Boolean flag indicating if message mentions price-related keywords"
      - name: product_type
        description: "Inferred product type: pill, cream, liquid, injection, drops, or other"
        tests:
          - accepted_values:
              values: ['pill', 'cream', 'liquid', 'injection', 'drops', 'other']
      - name: message_date
        description: "Timestamp of the message (for convenience, also available via dim_dates)"
      - name: hour_of_day
        description: "Hour of day when message was posted (0-23)"
      - name: loaded_at
        description: "Timestamp when the record was loaded into the database"

  - name: fct_enriched_messages
    description: |
      Fact table for messages enriched with YOLO object detection.
      Contains messages that have been processed through the YOLO enrichment pipeline.
    columns:
      - name: message_id
        description: "Primary key - unique message identifier"
        tests:
          - unique
          - not_null
      - name: detected_objects
        description: "JSONB array of detected object class names"
      - name: yolo_detections
        description: "JSONB array of full YOLO detection results with confidence scores and bounding boxes"
