version: 2

sources:
  - name: raw
    schema: public
    tables:
      - name: raw_messages
        description: "Raw messages from Telegram channels"
        columns:
          - name: message_id
            description: "Unique message identifier"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: message_date
            description: "Timestamp of the message"
          - name: message_text
            description: "Full text content of the message"
          - name: has_media
            description: "Whether the message contains media"
          - name: image_path
            description: "Path to downloaded image if applicable"
          - name: views
            description: "Number of views on the message"
          - name: forwards
            description: "Number of times the message was forwarded"
      - name: enriched_messages
        description: "Messages enriched with YOLO object detection"
        columns:
          - name: message_id
            description: "Unique message identifier"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: detected_objects
            description: "List of detected object classes (JSONB)"
          - name: yolo_detections
            description: "Full YOLO detection results with confidence scores (JSONB)"

models:
  - name: stg_messages
    description: "Staging model for cleaned messages"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel"
        tests:
          - not_null
      - name: message_date
        description: "Timestamp of the message"
        tests:
          - not_null
