version: 2

sources:
  - name: raw
    schema: raw
    description: "Raw data schema containing unprocessed Telegram messages"
    tables:
      - name: telegram_messages
        description: "Raw messages scraped from Telegram channels. This table contains unprocessed data directly from the data lake."
        columns:
          - name: message_id
            description: "Unique message identifier"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: message_date
            description: "Timestamp of the message"
          - name: message_text
            description: "Full text content of the message"
          - name: has_media
            description: "Whether the message contains media"
          - name: image_path
            description: "Path to downloaded image if applicable"
          - name: views
            description: "Number of views on the message"
          - name: forwards
            description: "Number of times the message was forwarded"
      - name: enriched_messages
        description: "Messages enriched with YOLO object detection"
        columns:
          - name: message_id
            description: "Unique message identifier"
          - name: channel_name
            description: "Name of the Telegram channel"
          - name: detected_objects
            description: "List of detected object classes (JSONB)"
          - name: yolo_detections
            description: "Full YOLO detection results with confidence scores (JSONB)"

models:
  - name: stg_messages
    description: |
      Staging model that cleans and standardizes raw Telegram messages.
      This model:
      - Casts data types appropriately (dates, integers, booleans)
      - Removes invalid records (null message_ids, empty channels, future dates)
      - Adds calculated fields (message_length, has_text, has_image)
      - Ensures non-negative values for views and forwards
      - Filters messages from the last 2 years
    columns:
      - name: message_id
        description: "Unique message identifier from Telegram"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Normalized channel name (lowercase, trimmed)"
        tests:
          - not_null
      - name: channel_title
        description: "Display title of the Telegram channel"
      - name: message_date
        description: "Timestamp when the message was posted (validated to be within reasonable range)"
        tests:
          - not_null
      - name: message_text
        description: "Cleaned text content of the message (trimmed, nulls converted to empty string)"
      - name: message_length
        description: "Length of the message text in characters (calculated field)"
      - name: has_text
        description: "Boolean flag indicating if message has non-empty text (calculated field)"
      - name: has_media
        description: "Boolean flag indicating if message contains media"
      - name: has_image
        description: "Boolean flag indicating if message has a downloaded image (calculated field)"
      - name: image_path
        description: "File path to downloaded image if present"
      - name: views
        description: "Number of views on the message (ensured to be non-negative)"
      - name: forwards
        description: "Number of times the message was forwarded (ensured to be non-negative)"
      - name: loaded_at
        description: "Timestamp when the record was loaded into the database"